In [6]:
import numpy as np

#Boolean Indexing in numPy
array_1 = np.array([10,20,30,40,50])
array_2 = np.array([5,10,15,20,25])
condition = array_1 > 25
condition_2 = array_1 < 25
print(condition)
print(array_1[condition])
print(array_2[condition_2])


[False False  True  True  True]
[30 40 50]
[ 5 10]


In [7]:
#another way

array_1 = np.array([10,20,30,40,50])
filtered_array = array_1[array_1 > 25]
print(filtered_array)


[30 40 50]


In [11]:
#combining multiple conditions

array_1 = np.array([10,20,30,40,50])
filtered_array = array_1[(array_1 > 25) & (array_1 < 40)] #and
print(filtered_array)

array_2 = np.array([5,10,15,20,25])
filtered_array_2 = array_2[(array_2 > 25) | (array_2 < 20)] #or
print(filtered_array_2)

array_3 = np.array([5,10,15,20,25])
filtered_array_3 = array_3[(array_3 > 25) ^ (array_3 < 20)] #xor
print(filtered_array_3)

[30]
[ 5 10 15]
[ 5 10 15]


In [16]:
#Array Initialization
array_1 = np.zeros(5)
print(array_1)  

array_2 = np.zeros((2,3))
print(array_2)

array_3 = np.zeros(3,dtype=float)
print(array_3)



[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0.]


In [19]:
#np.full
array_1 = np.full(5,10)
print(array_1)
print("-------------")

array_2 = np.full((2,3),10)
print(array_2)
print("-------------")

array_3 = np.full(3,10,dtype=float)
print(array_3)

[10 10 10 10 10]
-------------
[[10 10 10]
 [10 10 10]]
-------------
[10. 10. 10.]


In [25]:
#empty
array_2 = np.empty((2,3))
print(array_2)
print("-------------")



[[5.e-323 5.e-323 5.e-323]
 [5.e-323 5.e-323 5.e-323]]
-------------


In [30]:
#create a 1d numbpy array with arrays from 1 to 20 .use boolean index to extarct all even numbers.

array_1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(array_1[array_1 % 2 == 0])



[ 2  4  6  8 10 12 14 16 18 20]


In [31]:
#create a 1d  numpy array with elemnets 10,20,30,40,50.use boolen index into extract all elements greater than the mean of the array

array_1 = np.array([10,20,30,40,50])
mean = np.mean(array_1)
print(array_1[array_1 > mean])


[40 50]
