In [6]:
import numpy as np

#Boolean Indexing in numPy
array_1 = np.array([10,20,30,40,50])
array_2 = np.array([5,10,15,20,25])
condition = array_1 > 25
condition_2 = array_1 < 25
print(condition)
print(array_1[condition])
print(array_2[condition_2])


[False False  True  True  True]
[30 40 50]
[ 5 10]


In [7]:
#another way

array_1 = np.array([10,20,30,40,50])
filtered_array = array_1[array_1 > 25]
print(filtered_array)


[30 40 50]


In [11]:
#combining multiple conditions

array_1 = np.array([10,20,30,40,50])
filtered_array = array_1[(array_1 > 25) & (array_1 < 40)] #and
print(filtered_array)

array_2 = np.array([5,10,15,20,25])
filtered_array_2 = array_2[(array_2 > 25) | (array_2 < 20)] #or
print(filtered_array_2)

array_3 = np.array([5,10,15,20,25])
filtered_array_3 = array_3[(array_3 > 25) ^ (array_3 < 20)] #xor
print(filtered_array_3)

[30]
[ 5 10 15]
[ 5 10 15]


In [16]:
#Array Initialization
array_1 = np.zeros(5)
print(array_1)  

array_2 = np.zeros((2,3))
print(array_2)

array_3 = np.zeros(3,dtype=float)
print(array_3)



[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0.]


In [19]:
#np.full
array_1 = np.full(5,10)
print(array_1)
print("-------------")

array_2 = np.full((2,3),10)
print(array_2)
print("-------------")

array_3 = np.full(3,10,dtype=float)
print(array_3)

[10 10 10 10 10]
-------------
[[10 10 10]
 [10 10 10]]
-------------
[10. 10. 10.]


In [25]:
#empty
array_2 = np.empty((2,3))
print(array_2)
print("-------------")



[[5.e-323 5.e-323 5.e-323]
 [5.e-323 5.e-323 5.e-323]]
-------------


In [30]:
#create a 1d numbpy array with arrays from 1 to 20 .use boolean index to extarct all even numbers.

array_1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
print(array_1[array_1 % 2 == 0])



[ 2  4  6  8 10 12 14 16 18 20]


In [32]:
#create a 1d  numpy array with elemnets 10,20,30,40,50.use boolen index into extract all elements greater than the mean of the array

array_1 = np.array([10,20,30,40,50])
mean = np.mean(array_1)
print(mean)
print(array_1[array_1 > mean])


30.0
[40 50]


In [ ]:
#Pandas library
import pandas as pd
#creating DataFrame

data = {
    'Name':['Alice','Bob','Claire','David'],
    'Age':[25,30,35,40]
}
df = pd.DataFrame(data)
print(df)
print(type(df)) 
#accesing cells  in a dataframe
print(df.loc[1,"Name"])
print(df.iloc[1,0])#index location

     Name  Age
0   Alice   25
1     Bob   30
2  Claire   35
3   David   40
<class 'pandas.core.frame.DataFrame'>
Bob
Bob


In [13]:
#locate row

data = {
    'Name':['Alice','Bob','Claire','David'],
    'Age':[25,30,35,40]
}
df = pd.DataFrame(data)
print(df.loc[1])#returns the row 
print("-------------")
print(df.loc[[0,1]])#returns multiple rows


Name    Bob
Age      30
Name: 1, dtype: object
-------------
    Name  Age
0  Alice   25
1    Bob   30


In [12]:
#Named Index
import pandas as pd
data = {
    'Name':['Alice','Bob','Claire','David'],
    'Age':[25,30,35,40],
    'Address':['Matara','Hakmana','Kandy','Galle']
}
df =pd.DataFrame(data,index=['Row -1','Row -2','Row -3','Row -4'])
print(df)
print("-------------------")
print(df.loc[['Row -2','Row -3']])
print("-------------------")
print(df['Age'])
print("-------------------")
print("Dimension :",df.shape)
print("-------------------")
print(df.columns)
print(list(df.columns))


          Name  Age  Address
Row -1   Alice   25   Matara
Row -2     Bob   30  Hakmana
Row -3  Claire   35    Kandy
Row -4   David   40    Galle
-------------------
          Name  Age  Address
Row -2     Bob   30  Hakmana
Row -3  Claire   35    Kandy
-------------------
Row -1    25
Row -2    30
Row -3    35
Row -4    40
Name: Age, dtype: int64
-------------------
Dimension : (4, 3)
-------------------
Index(['Name', 'Age', 'Address'], dtype='object')
['Name', 'Age', 'Address']


In [2]:
#DataFrame size
import pandas as pd
df = pd.DataFrame({
    'Name':['Alice','Bob','Claire','David'],
    'Age':[25,30,35,40],
    'Address':['Matara','Hakmana','Kandy','Galle']
})
print(df.size)



12


In [4]:
#DataFrame.values
#returns the data as a numPy Array

import pandas as pd
df = pd.DataFrame({
    'Name':['Alice','Bob','Claire','David'],
    'Age':[25,30,35,40],
    'Address':['Matara','Hakmana','Kandy','Galle']
})
print(df.values)
print(type(df.values))



[['Alice' 25 'Matara']
 ['Bob' 30 'Hakmana']
 ['Claire' 35 'Kandy']
 ['David' 40 'Galle']]
<class 'numpy.ndarray'>


In [4]:
import pandas as pd
data = {
    'Name':['Alice','Bob','Claire','David'],
    'Age':[25,30,35,40],
    'Address':['Matara','Hakmana','Kandy','Galle']
}
df = pd.DataFrame(data)
print(len(df))


4


In [23]:
#you are a data anylists for a companay,the company has provide with you with the above table containig sales data,your task is to anlyist 
#the sales data using python and pandas to answers some key business quetions,
#calculate the total revenue for ecach order - add a new coloumn total revenue to store  the total revenue for each
#identify the best selling products
#find the product with the higehst total sales revenue
import pandas as pd
data ={
    "orderId" :['101','102','103','104','105'],
    "product" :['Laptop','SmartPhone','Desk chair','Monitor','Bookshelf'],
    "category" :['Electronics','Electronics','Furniture','Electronics','Furniture'],
    "quantity" :[2,5,10,4,2],
    "price per unit":[1000,800,150,200,300],
    "Region":["North","South","East","West","North"]
}
df = pd.DataFrame(data)
df["total revenue"] = df["quantity"] * df["price per unit"]
print(df)
# best_selling_product = max(df["quantity"])
# qty_sold_list = df["quantity"].values
# max_index = list(qty_sold_list).index(best_selling_product)
# print(df.loc[[max_index]])

best_sellling_product = df["total revenue"].max()
print(best_sellling_product)
print(df[df["total revenue"]== best_sellling_product])




  orderId     product     category  quantity  price per unit Region  \
0     101      Laptop  Electronics         2            1000  North   
1     102  SmartPhone  Electronics         5             800  South   
2     103  Desk chair    Furniture        10             150   East   
3     104     Monitor  Electronics         4             200   West   
4     105   Bookshelf    Furniture         2             300  North   

   total revenue  
0           2000  
1           4000  
2           1500  
3            800  
4            600  
4000
  orderId     product     category  quantity  price per unit Region  \
1     102  SmartPhone  Electronics         5             800  South   

   total revenue  
1           4000  


In [14]:
import pandas as pd

data ={
    'age':[24,90,10],
    'salary':[20000,90000,3000]
}
df = pd.DataFrame(data)
print(df.mean())
print("---------------")
print(df.sum())
print("---------------")
print(df.describe())



age          41.333333
salary    37666.666667
dtype: float64
---------------
age          124
salary    113000
dtype: int64
---------------
             age        salary
count   3.000000      3.000000
mean   41.333333  37666.666667
std    42.723920  46112.182049
min    10.000000   3000.000000
25%    17.000000  11500.000000
50%    24.000000  20000.000000
75%    57.000000  55000.000000
max    90.000000  90000.000000


In [16]:
import pandas as pd

data ={
    'name':["Tharu","Kusal","Sameera","Ashi"],
    'age':[24,90,10,45],
    'score':[20000,90000,3000,800]
}
df =pd.DataFrame(data)
print(df)
print('----------------------')
filtered_dataframe = df[df["age"]> 25]
print(filtered_dataframe,type(filtered_dataframe))

      name  age  score
0    Tharu   24  20000
1    Kusal   90  90000
2  Sameera   10   3000
3     Ashi   45    800
----------------------
    name  age  score
1  Kusal   90  90000
3   Ashi   45    800 <class 'pandas.core.frame.DataFrame'>


In [28]:
#adding new row end
import pandas as pd

df = pd.DataFrame({'A':[10,20],'B':[11,90]})
df.loc[len(df)] = [10,56]
print(df)


    A   B
0  10  11
1  20  90
2  10  56


In [34]:
#removing row and column
# if axis = 1 remove the column
# if axis = 0 remove the row
import pandas as pd

data ={
    'name':["Tharu","Kusal","Sameera","Ashi"],
    'age':[24,90,10,45],
    'score':[20000,90000,3000,800]
}
df =pd.DataFrame(data)
df_dropped = df.drop('age',axis=1)
print(df_dropped)
print('-------------------------')
df_dropped_row = df.drop(1,axis=0)
print(df_dropped_row)



      name  score
0    Tharu  20000
1    Kusal  90000
2  Sameera   3000
3     Ashi    800
-------------------------
      name  age  score
0    Tharu   24  20000
2  Sameera   10   3000
3     Ashi   45    800


In [1]:
#read CSV files

import pandas as pd

df = pd.read_csv('customers-100.csv')
print(df)

    Index      Customer Id First Name Last Name  \
0       1  DD37Cf93aecA6Dc     Sheryl    Baxter   
1       2  1Ef7b82A4CAAD10    Preston    Lozano   
2       3  6F94879bDAfE5a6        Roy     Berry   
3       4  5Cef8BFA16c5e3c      Linda     Olsen   
4       5  053d585Ab6b3159     Joanna    Bender   
..    ...              ...        ...       ...   
95     96  cb8E23e48d22Eae       Karl     Greer   
96     97  CeD220bdAaCfaDf       Lynn  Atkinson   
97     98  28CDbC0dFe4b1Db       Fred    Guerra   
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer   
99    100  2354a0E336A91A1   Clarence    Haynes   

                            Company               City  \
0                   Rasmussen Group       East Leonard   
1                       Vega-Gentry  East Jimmychester   
2                     Murillo-Perry      Isabelborough   
3   Dominguez, Mcmillan and Donovan         Bensonview   
4          Martin, Lang and Andrade     West Priscilla   
..                              ...    

In [9]:
#read CSV files

import pandas as pd

df1 = pd.read_json('example_1.json')
print(df1)

   fruit   size color
0  Apple  Large   Red
1  Apple  Large   Red
2  Apple  Large   Red
